; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES

#define MyAppName "WindowsNJQCA"
#define MyAppVersion "8.8"
#define MyAppPublisher "NewJaisa Tehnologies Ltd."
#define MyAppURL "https://newjaisa.com/"
#define SourceDir "C:\NJ\c_source_code"

[Setup]
AppId={{CB664719-0CB5-421D-ABD7-5A0674315607665594}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
OutputDir={#SourceDir}\installer_output
OutputBaseFilename=WindowsNJQCA_8.8
SetupIconFile={#SourceDir}\setup.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "{#SourceDir}\update.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\PresentMon-2.4.0-x64.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\django-todo\*"; DestDir: "{app}\django-todo"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\Amazon-Clone\*"; DestDir: "{app}\Amazon-Clone"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\db\*"; DestDir: "{app}\db"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\Hard Disk Sentinel\*"; DestDir: "{app}\Hard Disk Sentinel"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\ffmpeg\*"; DestDir: "{app}\ffmpeg"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\Geekbench 5\*"; DestDir: "{app}\Geekbench 5"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\OpenHardwareMonitor\*"; DestDir: "{app}\OpenHardwareMonitor"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\HeavyLoad\*"; DestDir: "{app}\HeavyLoad"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\Temp_Data\*"; DestDir: "{app}\Temp_Data\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\cacert.pem"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\NJQCA.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\libcurl-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\sqlite3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\WinBio.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\blur.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\run_heavy_load.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\AutopilotCheck.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\y-cruncher v0.8.7.9547b\*"; DestDir: "{app}\y-cruncher v0.8.7.9547b"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceDir}\runperformance.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\restart.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\web_scrap.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\screen_record.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\performance.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\slmgr.vbs"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\fingerprint.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\BlueScreenView.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\audio_similarity.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\ardunio.exe"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#SourceDir}\Setup.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\office_installer.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\NJCare.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\performance_monitor.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\wifitest.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\RunNJQCA.bat"; DestDir: "{userdesktop}"; Flags: ignoreversion
Source: "{#SourceDir}\run_njqca.bat"; DestDir: "{app}"; Flags: ignoreversion
;Source: "{#SourceDir}\Serial\*"; DestDir: "{app}\Serial"; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[UninstallRun]
Filename: "cmd.exe"; Parameters: "/c start /min ""{app}\Hard Disk Sentinel\removehds7.vbs"""; Flags: runascurrentuser waituntilterminated; RunOnceId: "Uninstall_HardDiskSentinel"
Filename: "cmd.exe"; Parameters: "/c rd /s /q ""{app}"""; Flags: runascurrentuser waituntilterminated; RunOnceId: "UninstallAppFiles"
Filename: "cmd.exe"; Parameters: "/c del /f /q ""{userdesktop}\RunNJQCA.bat"""; Flags: runascurrentuser waituntilterminated; RunOnceId: "UninstallShortcut"